### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by piyush161** [piyush161/account#3]
**Task to do**

- [ ] Flex styling in bootstrap.
- [ ] Find colour pallet for application.
- [ ] Opening modal from service in angular.
- [ ] Error Handling generic modal.(eg: Something went wrong message).
